//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarregamentoBloco
    {
        public int IDCarregamentoBloco { get; set; }
        public string Bloco { get; set; }
        public string Descricao { get; set; }
        public int IDRomaneio { get; set; }
        public string FrutaP { get; set; }
        public string FrutaM { get; set; }
        public string FrutaG { get; set; }
        public Nullable<decimal> PrecoP { get; set; }
        public Nullable<decimal> PrecoM { get; set; }
        public Nullable<decimal> PrecoG { get; set; }
        public Nullable<int> QtdP { get; set; }
        public Nullable<int> QtdM { get; set; }
        public Nullable<int> QtdG { get; set; }
        public Nullable<decimal> ValorUnitP { get; set; }
        public Nullable<decimal> ValorUnitM { get; set; }
        public Nullable<decimal> ValorUnitG { get; set; }
        public Nullable<decimal> TotalCarreg { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> TotalBloco { get; set; }
    }
}
